package com.knudsvig.centchallenge.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonFormat;

@Document(collection="dependent")
//! Container for Dependent details, to be used by Enrollee
public class Dependent {
	@Id
	//! The unique id of the Dependent, generated by the Mongo server
	private String id;
	//! The Full Name of the Enrollee
	private String name;
	
	@JsonFormat(pattern="MM-dd-yyyy")
	//! The birth date of the Dependent, saved in 'MM-dd-yyyy' format
	private Date birthDate;
	
	// CONSTRUCTORS
	
	public Dependent() {
		super();
	}
	
	/*
		\Constructor enabling initialization of name and birthDate
		\param name The value to assign to Dependent.name
		\param birthDate The value to assign to Dependent.birthDate
	 */
   
	public Dependent(String name, Date birthDate) {
		super();
		this.name = name;
		this.birthDate = birthDate;
	}
	
	// GETTERS AND SETTERS

	/*!
		\Getter/Setter for Dependent.id
		\return Dependent.id
	 */
   
	public String getId() {
		return id;
	}
	  
	public void setId(String id) {
		this.id = id;
	}
	
	/*
		\Getter/Setter for Name
		\return Dependent.name
	 */
   
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	/*
		\Getter/Setter for BirthDate
		\return Dependent.birthDate
	 */
   
	public Date getBirthDate() {
		return birthDate;
	}
	
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}
}
